"""``people`` collection models (DESIGN §7 sprites, §9 data model)."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, model_validator

from savepoint_server.models.base import MongoModel


class AvatarParams(BaseModel):
    """Deterministic parametric-sprite attributes read from a face (DESIGN §7).

    The same person always maps to the same sprite — these are the layered-kit
    selectors, never a raw photo.
    """

    model_config = ConfigDict(extra="forbid")

    skin_tone: str
    hair_color: str
    hair_style: str
    glasses: bool = False
    hat: str | None = None
    shirt_color: str


class Person(MongoModel):
    """A person you have met, rendered as a recurring pixel character."""

    local_id: str
    name: str | None = None
    avatar_params: AvatarParams
    # Speaker voiceprint (ECAPA, 192-d). Kept on-device where feasible (DESIGN §8);
    # optional here for enrolled speakers bound server-side.
    voice_embedding: list[float] | None = None
    # Gallery of recent face-attribute embeddings from the edge detector
    # (512-d, MobileFaceNet / w600k_mbf.onnx; see edge/types.py), newest last,
    # capped at services/ingest.py's _MAX_FACE_GALLERY. Stored from EdgeEvents
    # so a later detection under an unrecognized local_id can nearest-neighbour
    # match this Person instead of minting a duplicate (DESIGN §9; see
    # services/ingest.py's _find_matching_person). Kept as several recent
    # samples rather than one overwritten embedding — a single sample drifts
    # to whatever lighting/pose was last seen, making every subsequent match
    # a coin-flip and causing the same person to fragment into duplicates
    # over a day.
    face_embeddings: list[list[float]] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    favorite: bool = False
    first_seen: datetime | None = None
    last_seen: datetime | None = None
    notes: str | None = None
    # A short, cozy Stardew-toned character bio written by the LLM from this
    # person's events (SAV-36). Generated on demand via POST /people/{id}/bio and
    # served by the read API; ``None`` until first generated.
    bio: str | None = None
    # An AI pixel-art sprite-sheet manifest generated by PixelLab (SAV-61):
    #   {"tile": {"w": W, "h": H},
    #    "static": {"south": "south.png", "east": ..., "west": ..., "north": ...},
    #    "walk":   {"east": ["walk_east_0.png", "walk_east_1.png", ...]}}
    # Filenames are relative; the frontend builds URLs as
    # ``${API_BASE}/sprites/{local_id}/{filename}``. ``None`` until generated
    # (generation is config-gated + fire-and-forget on ingest; see services/pixellab.py).
    # Flows through the read API automatically (GET /people, /people/{id}).
    sprite: dict | None = None

    @model_validator(mode="before")
    @classmethod
    def _migrate_legacy_face_embedding(cls, data: Any) -> Any:
        """Fold the old single ``face_embedding`` field into the new gallery.

        Pre-gallery Mongo documents still have a ``face_embedding`` key; under
        this model's ``extra="forbid"`` that key alone would fail validation
        on read. Self-healing: the next upsert writes the document back out
        via the current field, so no separate migration script is needed.
        """
        if isinstance(data, dict) and "face_embedding" in data:
            data = dict(data)
            legacy = data.pop("face_embedding")
            if legacy is not None and not data.get("face_embeddings"):
                data["face_embeddings"] = [legacy]
        return data
